### ISSUE TITLE
Add tests for `panel.html`/state.js

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#37]
Approach that seems likely to work to add some tests for the frontend part of the app:

1. ~~read the `panel.html` file without letting panel.js run (it uses browser extension APIs), ie. strip out the script tag~~ 
2. ~~inject an `alpineState` instance (`window.alpineState = ...`)~~
3. ~~Inject a mock for `__alpineDevtool.port.postMessage`~~ #39 
4. ~~Send some fixture `components` data into `alpineState` & get everything to re-render (might need to call `Alpine.start()`)~~
5. ~~Should be ready to interact with the page and add some assertions.~~

Tests should at least contain all the bug/regression fixes that have been completed/are in progress:

- [x] https://github.com/Te7a-Houdini/alpinejs-devtools/issues/26, test: check postMessage sends numbers & that the input is type="number" #39 
- [x] https://github.com/Te7a-Houdini/alpinejs-devtools/issues/13, test: check postMessage sends booleans & that the input is type="checkbox" #39 
- [x] https://github.com/Te7a-Houdini/alpinejs-devtools/issues/6, test: check that clicking a "function" property doesn't show an input #39 
- [x] done as part of the fix PR https://github.com/Te7a-Houdini/alpinejs-devtools/issues/34, test: check that you can expand/collapse array/object properties

Other valuable tests (sanity checks):

- [x] can select a component to debug (ie. display its properties) #38 
- [x] can edit value of a top-level string property (check postMessage + value/type of input) #39 
- [x] can cancel editing #39 
- [x] can edit value of array values (eg. array of string)
- [x] can edit value of objects values (eg. object with a string property)
- ~~can edit value of array of object values~~
- ~~can edit value of object containing array values~~

Progress:

- [x] pick test runner + assertion library, currently looks like `jest` + `@testing-library/dom` is the best option to test an Alpine app since that's what Alpine.js itself uses #38 
- [x] add test harness (see step by step at start of issue) #38 
- [x] add sanity check tests (5/5) #38 #39 #45 
- [x] add tests for fixed bugs (3/3) #39 
- [x] integrate into CI, see #15 #38
