### ISSUE TITLE
Introduce viewing/editing data E2E tests

### ISSUE THREAD

**Issue by HugoDF** [alpine-collective/alpinejs-devtools#86]
Tests introduced as part of https://github.com/alpine-collective/alpinejs-devtools/issues/37 got removed, since then we've re-evaluated our testing strategy #81 

We need to add some Cypress tests to deal with:
- [x] selecting components (displays data + creates an overlay on the page see #84 )
- [x] viewing component state contents (function, HTMLElement #80 )
- [x] editing data (boolean, string, number) work in #116
- [ ] toggling expandable data types (array, object)
- [ ] editing arrays/objects

Scenarios ported from the original issue (should be easier to test now that we've got a backend.js + panel environment):
- can select a component to debug (ie. display its properties, on hover we get an overlay in the app)
- can edit value of a top-level string property 
- can cancel editing by pressing the icon
- can cancel editing with keyboard shortcut (does this actually work? I feel like we might have a regression on this)
- can confirm with keyboard shortcut (all the "can edit" tests will probably use the icon to commit the edit)
- can edit value of array values (eg. array of string)
- can edit value of objects values (eg. object with a string property)
- can edit value of array of object values
- can edit value of object containing array values
- can toggle arrays/objects view to open/close

Notes:
- feel free to add `data-testid`'s, there are already some in the `panel.html`

**Comment by HugoDF** [comment]
Another test case that might be useful is cleanup when we send a "shutdown" event to backend.js.

It should remove any DOM elements that we've added and stop receiving messages.

**Comment by KevinBatdorf** [comment]
You want to assign me some tests to implement? Better if they are "good introduction to the codebase" type tests for now.

**Comment by HugoDF** [comment]
> You want to assign me some tests to implement? Better if they are "good introduction to the codebase" type tests for now.

Sure, feel free to grab whatever's on that todo, "selecting components" is a good one to start with since you can't view/edit data if you haven't selected a component 😄

**Comment by HugoDF** [comment]
This has gotten a bit stale

the only outstanding scenarios are:
- toggling expandable data types (array, object)
- editing arrays/objects

Doesn't look like we're getting any issues with it so closing for now (we should add tests if we get any bugs with toggling)
